apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: knowledge-base-storage
  labels:
    app: knowledge-access-analytics
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2  # Adjust based on your OpenShift storage class